// Diagnostic assessments — one per unit
// Tests sample words from each pattern; score determines mastery level
window.DIAGNOSTICS = [
  {
    id: 'unit_digraphs',
    unit: 'Consonant Digraphs',
    weeks: [1, 2, 3, 4],
    description: "Tests recognition of sh, ch, th, wh, ph, ck. Read each word; child should say it correctly.",
    items: [
      { word: 'ship',  pattern: 'sh' },
      { word: 'fish',  pattern: 'sh' },
      { word: 'chip',  pattern: 'ch' },
      { word: 'much',  pattern: 'ch' },
      { word: 'this',  pattern: 'th' },
      { word: 'bath',  pattern: 'th' },
      { word: 'when',  pattern: 'wh' },
      { word: 'duck',  pattern: 'ck' },
      { word: 'rock',  pattern: 'ck' },
      { word: 'phone', pattern: 'ph' },
    ],
    spelling: ['ship', 'chop', 'thin', 'back'],
  },
  {
    id: 'unit_blends',
    unit: 'Blends & Endings',
    weeks: [5, 6, 7, 8],
    description: "Tests L-blends, R-blends, S-blends, and glued endings (-ank, -ink, -ing).",
    items: [
      { word: 'clap',  pattern: 'cl' },
      { word: 'flag',  pattern: 'fl' },
      { word: 'frog',  pattern: 'fr' },
      { word: 'trip',  pattern: 'tr' },
      { word: 'snap',  pattern: 'sn' },
      { word: 'stop',  pattern: 'st' },
      { word: 'bank',  pattern: '-ank' },
      { word: 'pink',  pattern: '-ink' },
      { word: 'ring',  pattern: '-ing' },
      { word: 'junk',  pattern: '-unk' },
    ],
    spelling: ['clap', 'frog', 'snap', 'pink'],
  },
  {
    id: 'unit_silent_e',
    unit: 'Silent E (VCe)',
    weeks: [9, 10, 11, 12],
    description: "Tests silent-E patterns for all 5 vowels.",
    items: [
      { word: 'cake',  pattern: 'a_e' },
      { word: 'made',  pattern: 'a_e' },
      { word: 'bike',  pattern: 'i_e' },
      { word: 'time',  pattern: 'i_e' },
      { word: 'home',  pattern: 'o_e' },
      { word: 'rope',  pattern: 'o_e' },
      { word: 'cube',  pattern: 'u_e' },
      { word: 'use',   pattern: 'u_e' },
      { word: 'these', pattern: 'e_e' },
      { word: 'snake', pattern: 'a_e' },
    ],
    spelling: ['cake', 'bike', 'home', 'cube'],
  },
  {
    id: 'unit_vowel_teams',
    unit: 'Vowel Teams',
    weeks: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    description: "The biggest unit — ee, ea, ai, ay, oa, ow, ou, oo (long & short), oi, oy.",
    items: [
      { word: 'tree',  pattern: 'ee' },
      { word: 'dream', pattern: 'ea' },
      { word: 'rain',  pattern: 'ai' },
      { word: 'play',  pattern: 'ay' },
      { word: 'boat',  pattern: 'oa' },
      { word: 'snow',  pattern: 'ow (long)' },
      { word: 'cloud', pattern: 'ou' },
      { word: 'moon',  pattern: 'oo (long)' },
      { word: 'book',  pattern: 'oo (short)' },
      { word: 'coin',  pattern: 'oi' },
      { word: 'boy',   pattern: 'oy' },
      { word: 'cow',   pattern: 'ow (/ow/)' },
    ],
    spelling: ['tree', 'rain', 'boat', 'moon', 'coin'],
  },
  {
    id: 'unit_r_controlled',
    unit: 'R-Controlled (Bossy R)',
    weeks: [23, 24, 25],
    description: "Tests ar, or, and the three /er/ spellings (er, ir, ur).",
    items: [
      { word: 'car',   pattern: 'ar' },
      { word: 'shark', pattern: 'ar' },
      { word: 'corn',  pattern: 'or' },
      { word: 'horn',  pattern: 'or' },
      { word: 'her',   pattern: 'er' },
      { word: 'bird',  pattern: 'ir' },
      { word: 'turn',  pattern: 'ur' },
      { word: 'first', pattern: 'ir' },
    ],
    spelling: ['car', 'corn', 'her', 'bird'],
  },
  {
    id: 'unit_advanced',
    unit: 'Soft & Advanced',
    weeks: [26, 27, 28, 29, 30],
    description: "Soft c/g, -tch/-dge, igh, y as long E/I, plurals.",
    items: [
      { word: 'face',   pattern: 'soft c' },
      { word: 'gem',    pattern: 'soft g' },
      { word: 'catch',  pattern: '-tch' },
      { word: 'bridge', pattern: '-dge' },
      { word: 'light',  pattern: 'igh' },
      { word: 'sky',    pattern: 'y = long I' },
      { word: 'happy',  pattern: 'y = long E' },
      { word: 'boxes',  pattern: '-es plural' },
    ],
    spelling: ['face', 'catch', 'light', 'happy'],
  },
];
